# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import os.path

class Persona:

    def __init__(self):
        self.__DI = ""
        self.__N = ""
        self.__A = ""
    def getDI(self):
        return self.__DI
    def getN(self):
        return self.__N
    def getA(self):
        return self.__A

    def setDI(self,DI):
        self.__DI=DI
                
    def setN(self,N):
        self.__N=N
        
    def setA(self,A):
        self.__A=A
        
class Estudiante(Persona):
    def __init__(self):
        self.__CP = ""
        self.__CE = ""
        self.__PA = ""

    def getCP(self):
        return self.__CP
    def getCE(self):
        return self.__CE
    def getPA(self):
        return self.__PA


    def setCP(self,CP):
        self.__CP=CP

    def setCE(self,CE):
        self.__CE=CE
               
    def setPA(self,PA):
        self.__PA = PA

class Ui_SIA(object):
    def setupUi(self, SIA):
        SIA.setObjectName("SIA")
        SIA.setEnabled(True)
        SIA.resize(762, 495)
        SIA.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(SIA)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(340, 420, 111, 41))
        self.pushButton_4.setBaseSize(QtCore.QSize(9, 0))
        self.pushButton_4.setAutoRepeatDelay(298)
        self.pushButton_4.setObjectName("pushButton_4")
        self.Volver = QtWidgets.QPushButton(self.centralwidget)
        self.Volver.setGeometry(QtCore.QRect(110, 430, 112, 32))
        self.Volver.setObjectName("Volver")
        self.Menu = QtWidgets.QWidget(self.centralwidget)
        self.Menu.setGeometry(QtCore.QRect(210, 110, 421, 301))
        self.Menu.setObjectName("Menu")
        self.pushButton = QtWidgets.QPushButton(self.Menu)
        self.pushButton.setGeometry(QtCore.QRect(80, 30, 211, 51))
        self.pushButton.setMouseTracking(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.Menu)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 90, 211, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.Menu)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 150, 211, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.Buscador = QtWidgets.QWidget(self.centralwidget)
        self.Buscador.setGeometry(QtCore.QRect(10, 20, 711, 391))
        self.Buscador.setObjectName("Buscador")
        self.label_8 = QtWidgets.QLabel(self.Buscador)
        self.label_8.setGeometry(QtCore.QRect(100, 20, 71, 21))
        self.label_8.setObjectName("label_8")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.Buscador)
        self.tableWidget_2.setEnabled(True)
        self.tableWidget_2.setGeometry(QtCore.QRect(19, 90, 711, 281))
        self.tableWidget_2.setAutoScroll(True)
        self.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_2.setTabKeyNavigation(True)
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(7)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.Buscador)
        self.lineEdit_6.setGeometry(QtCore.QRect(190, 20, 113, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.Buscador)
        self.pushButton_7.setGeometry(QtCore.QRect(170, 50, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.Datos = QtWidgets.QWidget(self.centralwidget)
        self.Datos.setEnabled(True)
        self.Datos.setGeometry(QtCore.QRect(150, 50, 471, 361))
        self.Datos.setObjectName("Datos")
        self.PAPA = QtWidgets.QLineEdit(self.Datos)
        self.PAPA.setGeometry(QtCore.QRect(280, 210, 113, 20))
        self.PAPA.setObjectName("PAPA")
        self.Documento = QtWidgets.QLineEdit(self.Datos)
        self.Documento.setGeometry(QtCore.QRect(280, 50, 113, 20))
        self.Documento.setObjectName("Documento")
        self.label_6 = QtWidgets.QLabel(self.Datos)
        self.label_6.setGeometry(QtCore.QRect(40, 210, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.Codigo = QtWidgets.QLineEdit(self.Datos)
        self.Codigo.setGeometry(QtCore.QRect(280, 150, 113, 20))
        self.Codigo.setObjectName("Codigo")
        self.Guardar = QtWidgets.QPushButton(self.Datos)
        self.Guardar.setGeometry(QtCore.QRect(200, 260, 111, 41))
        self.Guardar.setObjectName("Guardar")
        self.comboBox = QtWidgets.QComboBox(self.Datos)
        self.comboBox.setGeometry(QtCore.QRect(280, 180, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.Datos)
        self.label_3.setGeometry(QtCore.QRect(40, 140, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.Datos)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Nombre = QtWidgets.QLineEdit(self.Datos)
        self.Nombre.setGeometry(QtCore.QRect(280, 80, 113, 20))
        self.Nombre.setObjectName("Nombre")
        self.label_5 = QtWidgets.QLabel(self.Datos)
        self.label_5.setGeometry(QtCore.QRect(40, 110, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.Datos)
        self.label_4.setGeometry(QtCore.QRect(40, 180, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.Apellido = QtWidgets.QLineEdit(self.Datos)
        self.Apellido.setGeometry(QtCore.QRect(280, 110, 113, 20))
        self.Apellido.setObjectName("Apellido")
        self.label = QtWidgets.QLabel(self.Datos)
        self.label.setGeometry(QtCore.QRect(40, 50, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.BaseD = QtWidgets.QWidget(self.centralwidget)
        self.BaseD.setGeometry(QtCore.QRect(0, 0, 761, 421))
        self.BaseD.setObjectName("BaseD")
        self.tableWidget = QtWidgets.QTableWidget(self.BaseD)
        self.tableWidget.setGeometry(QtCore.QRect(29, 110, 711, 281))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.label_7 = QtWidgets.QLabel(self.BaseD)
        self.label_7.setGeometry(QtCore.QRect(100, 30, 81, 31))
        self.label_7.setObjectName("label_7")
        self.comboBox_2 = QtWidgets.QComboBox(self.BaseD)
        self.comboBox_2.setGeometry(QtCore.QRect(190, 30, 221, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.pushButton_6 = QtWidgets.QPushButton(self.BaseD)
        self.pushButton_6.setGeometry(QtCore.QRect(440, 30, 81, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.BANDERA = QtWidgets.QLabel(self.centralwidget)
        self.BANDERA.setGeometry(QtCore.QRect(410, 30, 121, 61))
        self.BANDERA.hide()
        self.BANDERA.setObjectName("BANDERA")
        self.BANDERA.raise_()
        self.Buscador.raise_()
        self.pushButton_4.raise_()
        self.Volver.raise_()
        self.BaseD.raise_()
        self.Menu.raise_()
        self.Datos.raise_()
        SIA.setCentralWidget(self.centralwidget)

        self.retranslateUi(SIA)
        self.pushButton.clicked.connect(self.Datos.show)
        self.pushButton.clicked.connect(self.Menu.hide)
        self.pushButton_2.clicked.connect(self.Menu.hide)
        self.pushButton_3.clicked.connect(self.Buscador.show)
        self.pushButton_3.clicked.connect(self.Menu.hide)
        self.pushButton_3.clicked.connect(self.Volver.show)
        self.pushButton_2.clicked.connect(self.Volver.show)
        self.pushButton.clicked.connect(self.Volver.show)
        self.Volver.clicked.connect(self.Menu.show)
        self.Volver.clicked.connect(self.Buscador.hide)
        self.Volver.clicked.connect(self.BaseD.hide)
        self.pushButton_2.clicked.connect(self.BaseD.show)
        self.Volver.clicked.connect(self.Datos.hide)
        self.Volver.clicked.connect(self.Volver.hide)
        self.pushButton_4.clicked.connect(SIA.close)
        self.Guardar.clicked.connect(self.btnClicked)
        QtCore.QMetaObject.connectSlotsByName(SIA)

    def btnClicked(self):
        Documento=self.Documento.text()
        Nombre=self.Nombre.text()
        Apellido=self.Apellido.text()
        Codigo=self.Codigo.text()
        PAPA=self.PAPA.text()
        comboBox=self.comboBox.currentText()


        
        mi_estudiante = Estudiante()
        mi_estudiante.setDI(Documento)
        mi_estudiante.setN(Nombre)
        mi_estudiante.setA(Apellido)
        mi_estudiante.setCP(Codigo)
        mi_estudiante.setCE(comboBox)
        mi_estudiante.setPA(PAPA)

        diccionario = mi_estudiante.getDI() + ";" + mi_estudiante.getN() + ";" + mi_estudiante.getA() + ";" + mi_estudiante.getCP() + ";" + mi_estudiante.getCE() + ";" + mi_estudiante.getPA()  # Creación del diccionario de la materia

        if not os.path.isfile("BD-Estudiantes.txt"):  # Verificación de que la base de datos exista usando "isfile" de la libreria os.path , si existe el archivo el valor es True, sino False .Por lo tanto si el archivo no existe entonces entra a la condición
            BDM = open("BD-Estudiantes.txt","w")  # Este modo abre el archivo para escritura. Si el archivo no existe, crea un nuevo archivo.
            numerodeestudiantes = 1  # Establece el número de materias en 1
            BDM.write(str(numerodeestudiantes) + ";" + str(diccionario) + "\n")  # Escribe los datos de la primera materia
            BDM.close()  # Cierra el archivo

            with open('ContadorBD-Estudiantes.txt','w') as file:  # Este modo abre el archivo para escritura. Si el archivo no existe, crea un nuevo archivo.
                file.write(str(numerodeestudiantes))  # Escribe los datos  iniciales del numero de materias en la abse de datos


        else:  # Si el archivo ya existe se entra a esta condicion
            with open('ContadorBD-Estudiantes.txt','r') as file:  # Abre el archivo del contador de materias en modo lectura
                numerodeestudiantes = file.read()  # Almacena el numero de materias leyendo el archivo
            numerodeestudiantes = int(numerodeestudiantes) + 1  # Como se hizo una adición a la base de datos de materias entonces se aumenta el contador en 1

            with open("BD-Estudiantes.txt","a") as file:  # Abrir archivo en modo adjuntar. Si el archivo no existe, crea un nuevo archivo.
                file.write(str(numerodeestudiantes) + ";" + str(diccionario) + "\n")  # Escribe los datos de la siguiente materia
        
        self.Documento.clear()
        self.Nombre.clear()
        self.Apellido.clear()
        self.Codigo.clear()
        self.PAPA.clear()


    def retranslateUi(self, SIA):
        _translate = QtCore.QCoreApplication.translate
        SIA.setWindowTitle(_translate("SIA", "MainWindow"))
        self.pushButton_4.setText(_translate("SIA", "Salir "))
        self.Volver.setText(_translate("SIA", "Volver"))
        self.pushButton.setText(_translate("SIA", "Ingresar Estudiante"))
        self.pushButton_2.setText(_translate("SIA", "Ver base de datos Estudiante"))
        self.pushButton_3.setText(_translate("SIA", "Buscar"))
        self.label_8.setText(_translate("SIA", "Buscar por"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("SIA", "Índice"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("SIA", "Documento de \n"
"identidad"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("SIA", "Nombre"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("SIA", "Apellido"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("SIA", "Código de \n"
"plan de estudio"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("SIA", "Calidad de\n"
"estudiante"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("SIA", "PAPA actual"))
        self.pushButton_7.setText(_translate("SIA", "Buscar"))
        self.label_6.setText(_translate("SIA", "PAPA actual"))
        self.Guardar.setText(_translate("SIA", "Guardar"))
        self.comboBox.setItemText(0, _translate("SIA", "Seleccionar"))
        self.comboBox.setItemText(1, _translate("SIA", "Matriculado"))
        self.comboBox.setItemText(2, _translate("SIA", "Graduado"))
        self.comboBox.setItemText(3, _translate("SIA", "Pérdida de cupo"))
        self.label_3.setText(_translate("SIA", "Código de plan de estudios"))
        self.label_2.setText(_translate("SIA", "Nombre "))
        self.label_5.setText(_translate("SIA", "Apellido"))
        self.label_4.setText(_translate("SIA", "Calidad de estudiante"))
        self.label.setText(_translate("SIA", "Documento de identidad"))
        self.BANDERA.setText(_translate("SIA", "ERROR"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("SIA", "Índice "))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("SIA", "Documento de \n"
"identidad"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("SIA", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("SIA", "Apellido"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("SIA", "Código plan \n"
"de estudios "))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("SIA", "Calidad de \n"
"estudiante "))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("SIA", "PAPA actual"))
        self.label_7.setText(_translate("SIA", "Ordenar por"))
        self.comboBox_2.setItemText(0, _translate("SIA", "Documento de identidad"))
        self.comboBox_2.setItemText(1, _translate("SIA", "Nombre"))
        self.comboBox_2.setItemText(2, _translate("SIA", "Apellido"))
        self.comboBox_2.setItemText(3, _translate("SIA", "Código plan de estudios"))
        self.comboBox_2.setItemText(4, _translate("SIA", "Calidad de estudiante"))
        self.comboBox_2.setItemText(5, _translate("SIA", "PAPA actual"))
        self.pushButton_6.setText(_translate("SIA", "Ordenar"))
        
